---
# tasks file for docker-install
- name: Docker | Install dependencies
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: true
  become: true

- name: Docker | Add GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Docker | Add docker repository to apt
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  become: true

- name: Docker | Install docker
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: true
  become: true

- name: Docker | Check docker is active
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  become: true

- name: Docker | Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present
  become: true

- name: Docker | Add current user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  become: true

- name: Docker | Install docker-compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'
  become: true

- name: Docker | Change file ownership, group and permissions
  ansible.builtin.file:
    path: /usr/local/bin/docker-compose
    owner: "{{ ansible_user }}"
  become: true